### PR TITLE
Persist colors between visits

### PR DESCRIPTION
**Pull request by zephraph**
👋 I really love this icon set. 

I find myself coming back often to update more of my icons, but I've been a little frustrated about having to re-add the colors every time. 

This PR just remembers people's choice between visits. The implementation is _very_ naive and I can update it to be more robust if you prefer.  

<details>
 <summary>Here's the icons in all their glory if you wanna see my setup</summary>

image

</details>

### CODE REVIEW

**Comment by pacocoursey** [comment]
Thanks for this! I was just thinking it would be a nice feature.

Unfortunately this is going to require some more work because a Next.js app can be rendered server-side (which has no access to `window` or localStorage).

Right now I see two possible solutions: disable SSR and just serve everything client side, or use cookies instead of localStorage. Thoughts?

**Comment by pacocoursey** [comment]
Also your dock setup is amazing, I love the accented finder icon 😍I don't know how many of those menu bar icons you use, but I'd definitely recommend [Vanilla](https://matthewpalmer.net/vanilla/) to hide the ones you don't use.

**Comment by zephraph** [comment]
@pacocoursey I pushed an update that'll protect from window not being defined in the context. It should be safe for SSR. 

Thanks for the tip on Vanilla! I'm learning all sorts of new things.

**Comment by pacocoursey** [comment]
Looks like that does it! Thanks!

**Pull request merged**
