### PR TITLE
Add icon for Brave Browser

### PR DESCRIPTION
**Pull request by arggh**
I noticed there was no icon for the Brave Browser, so I made one. I hope you like it.

I tried to align it vertically somewhat similarly to a few of the existing icons:

comparison

### CODE REVIEW

**Comment by pacocoursey** [comment]
Sorry for the delay. It looks great, thank you for the contribution!

**Comment by arggh** [comment]
I'm glad you like it!

I just lost the icon as Brave updated itself, so I headed over to dusk.now.sh to download it again - but it's nowhere to be found. Is the site updated on a separate schedule, instead of after every merge to master?

**Comment by pacocoursey** [comment]
Unfortunately I have to manually update it and redeploy the site, sorry. I did that last night, so it should be up now @arggh

**Comment by arggh** [comment]
No worries, just checking!

**Pull request merged**
