### PR TITLE
add icon: slack2

### PR DESCRIPTION
**Pull request by b-b0t**
slack rebranded, might want to make this the primary icon but i'll leave that up to you.

### CODE REVIEW

**Comment by b-b0t** [comment]
added snippetslab, really cool code management library

**Comment by pacocoursey** [comment]
Again, this looks perfect. Was just about to update the Slack one.

I'll update the website and deploy a new version in the next few hours.

**Comment by b-b0t** [comment]
Awesome. I'm going to wait for the new office icons as they're also doing a rebrand before I submit those.

Please can you design Transmit and Fork when you get a chance (only ones I really don't know where to start), final missing pieces of my dock puzzle :)

**Comment by b-b0t** [comment]
office-icons-2018

Would the icons contain the letter or the panel? I know you wanted all text to be in Gilroy so maybe can start with them.

**Pull request merged**
